import express from 'express';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3000;

// Trust reverse proxy (Nginx / Cloudflare / Apache)
app.set('trust proxy', 1);

// Stripe webhook requires raw Buffer for cryptographic signature verification
app.post(['/api/stripe-webhook', '/api/stripe/webhook'], express.raw({ type: '*/*', limit: '2mb' }), async (req, res) => {
  try {
    req.rawBody = req.body;
    const { default: handler } = await import('./api/stripe-webhook.js');
    await handler(req, res);
  } catch (error) {
    console.error('[stripe-webhook error]', error);
    if (!res.headersSent) res.status(500).json({ error: error.message });
  }
});

// JSON body parser for all other /api endpoints (max 10MB to accommodate base64 payment receipts)
app.use('/api', express.json({ limit: '10mb' }));

// Known API rewrites (matching vercel.json)
const API_REWRITES = {
  'stripe/webhook': 'stripe-webhook',
  'verify-stripe-payment': 'order-status',
  'capture-paypal-order': 'order-status',
};

// Universal API request handler
app.all('/api/*', async (req, res, next) => {
  let endpoint = req.path.replace(/^\/api\//, '').split('?')[0];
  if (API_REWRITES[endpoint]) {
    endpoint = API_REWRITES[endpoint];
  }

  const filePath = path.resolve(__dirname, `api/${endpoint}.js`);
  if (!fs.existsSync(filePath)) {
    return res.status(404).json({ error: `API endpoint '/api/${endpoint}' not found` });
  }

  try {
    const { default: handler } = await import(`./api/${endpoint}.js`);
    if (typeof handler === 'function') {
      await handler(req, res);
    } else {
      res.status(500).json({ error: 'Handler is not callable' });
    }
  } catch (error) {
    console.error(`[API error: /api/${endpoint}]`, error);
    if (!res.headersSent) {
      res.status(500).json({ error: error.message || 'Internal server error' });
    }
  }
});

// Serve frontend static files from dist/ (generated by `npm run build`)
const distPath = path.resolve(__dirname, 'dist');
if (fs.existsSync(distPath)) {
  app.use(express.static(distPath, {
    maxAge: '1d',
    index: false,
    setHeaders: (res, filePath) => {
      // Immutable caching for Vite hashed assets
      if (filePath.includes(`${path.sep}assets${path.sep}`)) {
        res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
      }
    },
  }));
}

// SPA fallback: any non-API route serves index.html
app.get('*', (req, res) => {
  const indexPath = path.resolve(distPath, 'index.html');
  if (fs.existsSync(indexPath)) {
    res.sendFile(indexPath);
  } else {
    res.status(503).send(`
      <!DOCTYPE html>
      <html>
        <head><title>Build Required</title></head>
        <body style="font-family: sans-serif; text-align: center; padding: 50px;">
          <h2>Application build not found</h2>
          <p>Please run <code>npm run build</code> to compile the frontend assets before starting the server.</p>
        </body>
      </html>
    `);
  }
});

app.listen(PORT, () => {
  console.log(`\n======================================================`);
  console.log(` DVDs Zone Production Server running on port ${PORT}`);
  console.log(` Base site URL: ${process.env.SITE_URL || `http://localhost:${PORT}`}`);
  console.log(`======================================================\n`);
});
